
package fileclient.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InfoNotFoundException", targetNamespace = "http://fileserver/")
public class InfoNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InfoNotFoundException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InfoNotFoundException_Exception(String message, InfoNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InfoNotFoundException_Exception(String message, InfoNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fileclient.ws.InfoNotFoundException
     */
    public InfoNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
