
package fileclient.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UserPermissionException", targetNamespace = "http://fileserver/")
public class UserPermissionException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UserPermissionException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UserPermissionException_Exception(String message, UserPermissionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UserPermissionException_Exception(String message, UserPermissionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fileclient.ws.UserPermissionException
     */
    public UserPermissionException getFaultInfo() {
        return faultInfo;
    }

}
