
package fileclient.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSFileServerService", targetNamespace = "http://fileserver/", wsdlLocation = "http://192.168.1.4:8080/FileServer?wsdl")
public class WSFileServerService
    extends Service
{

    private final static URL WSFILESERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSFILESERVERSERVICE_EXCEPTION;
    private final static QName WSFILESERVERSERVICE_QNAME = new QName("http://fileserver/", "WSFileServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.4:8080/FileServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSFILESERVERSERVICE_WSDL_LOCATION = url;
        WSFILESERVERSERVICE_EXCEPTION = e;
    }

    public WSFileServerService() {
        super(__getWsdlLocation(), WSFILESERVERSERVICE_QNAME);
    }

    public WSFileServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSFILESERVERSERVICE_QNAME, features);
    }

    public WSFileServerService(URL wsdlLocation) {
        super(wsdlLocation, WSFILESERVERSERVICE_QNAME);
    }

    public WSFileServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSFILESERVERSERVICE_QNAME, features);
    }

    public WSFileServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSFileServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSFileServer
     */
    @WebEndpoint(name = "WSFileServerPort")
    public WSFileServer getWSFileServerPort() {
        return super.getPort(new QName("http://fileserver/", "WSFileServerPort"), WSFileServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSFileServer
     */
    @WebEndpoint(name = "WSFileServerPort")
    public WSFileServer getWSFileServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fileserver/", "WSFileServerPort"), WSFileServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSFILESERVERSERVICE_EXCEPTION!= null) {
            throw WSFILESERVERSERVICE_EXCEPTION;
        }
        return WSFILESERVERSERVICE_WSDL_LOCATION;
    }

}
